name: wisdom
adopt-info: wisdom
summary: Wisdom from the terminal
description: |
  Wisdom from wise people, straight from the terminal.

base: core18
grade: stable 
confinement: strict

license: MIT

apps:
  wisdom:
    command: wisdom
    environment:
      LC_ALL: C.UTF-8
     
parts: 
  wisdom:
    source: https://github.com/kz6fittycent/wisdom
    source-type: git
    plugin: python
    python-version: python3
    
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"
      
    build-packages:
      - python3
      
    stage-packages:
      - python3
