name: wisdom # check to see if it's available
version: '1.2+git' # this is freakin' awesome
summary: Wisdom from the terminal # 79 char long summary
description: |
  Wisdom from wise people, straight from the terminal.
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs

apps:
  wisdom:
    command: wisdom
    plugs:
      - home
     
parts: 
  my-part:
    source: https://github.com/kz6fittycent/wisdom
    source-type: git
    plugin: python3
    
    build-packages:
      - python3
      
    stage-packages:
      - python3
